# Generated by Django 4.0.5 on 2022-06-13 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boleta',
            fields=[
                ('id_boleta', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('desc', models.TextField(max_length=1000)),
                ('stock', models.IntegerField()),
                ('categoria', models.IntegerField(choices=[[0, 'Macetas'], [1, 'Plantas'], [2, 'Herramientas'], [3, 'Tierras']])),
                ('FotoProducto', models.ImageField(null=True, upload_to='productos')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombreusuario', models.CharField(max_length=100)),
                ('nombrereal', models.CharField(max_length=10)),
                ('RUT', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=30)),
                ('nacimiento', models.DateField()),
                ('genero', models.IntegerField(choices=[[0, 'Seleccione'], [1, 'Hombre'], [2, 'Mujer'], [3, 'No especificado']])),
                ('telefono', models.CharField(max_length=100)),
                ('Direccion', models.TextField(max_length=100)),
                ('comuna', models.IntegerField(choices=[[0, 'Peñaflor'], [1, 'Cerrillos'], [2, 'Cerro Navia'], [3, 'Conchalí'], [4, 'El Bosque'], [5, 'Estación Central'], [6, 'Huechuraba'], [7, 'Independencia'], [8, 'La Cisterna'], [9, 'La Florida'], [10, 'La Granja'], [11, 'La Pintana'], [12, 'La Reina'], [13, 'Las Condes'], [14, 'Lo Barnechea'], [15, 'Lo Espejo'], [16, 'Lo Prado'], [17, 'Macul'], [18, 'Maipú'], [19, 'Ñuñoa'], [20, 'Pedro Aguirre Cerda'], [21, 'Peñalolén'], [22, 'Providencia'], [23, 'Pudahuel'], [24, 'Quilicura'], [25, 'Quinta Normal'], [26, 'Recoleta'], [27, 'Renca'], [28, 'San Joaquín'], [29, 'San Miguel'], [30, 'San Ramón'], [31, 'Vitacura'], [32, 'Puente Alto'], [33, 'Pirque'], [34, 'San José de Maipo'], [35, 'Colina'], [36, 'Lampa'], [37, 'Tiltil'], [38, 'San Bernardo'], [39, 'Buin'], [40, 'Calera de Tango'], [41, 'Paine'], [42, 'Melipilla'], [43, 'Alhué'], [44, 'Curacaví'], [45, 'María Pinto'], [46, 'San Pedro'], [47, 'Talagante'], [48, 'El Monte'], [49, 'Isla de Maipo'], [50, 'Padre Hurtado']])),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('preciodetalle', models.IntegerField()),
                ('fechadetalle', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('id_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProyecto.producto')),
            ],
        ),
    ]
