# Generated by Django 4.0.5 on 2022-06-12 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreBoleta', models.TextField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('desc', models.TextField(max_length=1000)),
                ('stock', models.IntegerField()),
                ('categoria', models.IntegerField(choices=[[0, 'Seleccione'], [1, 'Macetas'], [2, 'Plantas'], [3, 'Herramientas'], [4, 'Tierras']])),
                ('FotoProducto', models.ImageField(null=True, upload_to='productos')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombreusuario', models.CharField(max_length=100)),
                ('nombrereal', models.CharField(max_length=10)),
                ('RUT', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=30)),
                ('nacimiento', models.DateField()),
                ('genero', models.IntegerField(choices=[[0, 'Seleccione'], [1, 'Hombre'], [2, 'Mujer'], [3, 'No especificado']])),
                ('telefono', models.CharField(max_length=100)),
                ('Direccion', models.TextField(max_length=100)),
                ('comuna', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('preciodetalle', models.IntegerField()),
                ('fechadetalle', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('id_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProyecto.producto')),
            ],
        ),
    ]
